<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Compile Update="Forms\Main.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Useront\TovarControl.cs">
        <SubType>UserControl</SubType>
      </Compile>
      <Compile Update="Forms\Autor.cs">
        <SubType>Form</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="EntityFramework">
        <HintPath>..\packages\EntityFramework.6.5.1\lib\net45\EntityFramework.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\" />
    </ItemGroup>

</Project>