//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTrade.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public double OrderID { get; set; }
        public Nullable<double> OrderArticule { get; set; }
        public Nullable<double> OrderPostavjic { get; set; }
        public Nullable<System.DateTime> OrderDateGo { get; set; }
        public Nullable<System.DateTime> OrderDateDiv { get; set; }
        public Nullable<int> OrderPunct { get; set; }
        public Nullable<double> OrderCod { get; set; }
        public Nullable<double> OrderStatus { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual OrderProduct OrderProduct { get; set; }
        public virtual Status Status { get; set; }
    }
}
