//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTrade.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPunkt
    {
        public int OrderPunktID { get; set; }
        public Nullable<double> OrderPunktIndex { get; set; }
        public string OrderPunktName { get; set; }
        public string OrderPunktylica { get; set; }
    }
}
