//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTrade.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> ProductCategory { get; set; }
        public string ProductPhoto { get; set; }
        public Nullable<double> ProductManufacturer { get; set; }
        public Nullable<double> ProductSupplier { get; set; }
        public Nullable<double> ProductCost { get; set; }
        public Nullable<double> ProductDiscountAmount { get; set; }
        public Nullable<double> ProductQuantityInStock { get; set; }
        public string ProductUnitMeasurement { get; set; }
        public Nullable<double> ProductCurrentDiscount { get; set; }
    
        public virtual CategoryProd CategoryProd { get; set; }
        public virtual ProductManufacturer ProductManufacturer1 { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
